import { v4 as uuid } from "uuid"

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    id: uuid(),
    title: "One Piece",
    img: "https://i.ibb.co/M6R0ym4/one-piece.webp",
    author: "Eiichiro Oda",
    category: "Adventure",
    published: 1997,
    rating: 5,
    price: 250,
    originalPrice: 399,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "Attack on Titan",
    img: "https://i.ibb.co/gwgsD62/Attack-of-titan.jpg",
    author: "Hajime Isayama",
    category: "Action",
    published: 2009,
    rating: 4.0,
    price: 275,
    originalPrice: 350,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "Naruto",
    img: "https://i.ibb.co/fDnMm5V/Naruto.jpg",
    author: "Masashi Kishimoto",
    category: "Adventure",
    published: 1999,
    rating: 5,
    price: 200,
    originalPrice: 399,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "Death Note",
    img: "https://i.ibb.co/H7zzSPK/Death-Note.jpg",
    author: "Tsugumi Ohba",
    category: "Drama",
    published: 2003,
    rating: 3.9,
    price: 650,
    originalPrice: 999,
    deliveryTime: "2-4 business days",
    ratings: 4.6
  },
  {
    id: uuid(),
    title: "Dragon Ball",
    img: "https://i.ibb.co/LvknnNs/ragon-Ball-Z.png",
    author: "Akira Toriyama",
    category: "Adventure",
    published: 1984,
    rating: 2.5,
    price: 599,
    originalPrice: 899,
    deliveryTime: "2-4 business days",
    ratings: 4.6
  },
  {
    id: uuid(),
    title: "Fullmetal Alchemist",
    img: "https://i.ibb.co/BC1kZDQ/Fullmetal-Alchemist.jpg",
    author: "Hiromu Arakawa",
    category: "Action",
    published: 2001,
    rating: 4.1,
    price: 425,
    originalPrice: 799,
    deliveryTime: "2-4 business days",
    ratings: 4.6
  },
  {
    id: uuid(),
    title: "Bleach",
    img: "https://i.ibb.co/ct0NYbF/Bleach.jpg",
    author: "Tite Kubo",
    category: "Action",
    published: 2001,
    rating: 3.2,
    price: 200,
    originalPrice: 499,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "One Punch Man",
    img: "https://i.ibb.co/7XSgkcK/One-Punch-Man.jpg",
    author: "ONE",
    category: "Drama",
    published: 2009,
    rating: 3.7,
    price: 250,
    originalPrice: 399,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "My Hero Academia",
    img: "https://i.ibb.co/xs6J8QN/My-Hero-Academia.jpg",
    author: "Kohei Horikoshi",
    category: "Drama",
    published: 2014,
    rating: 3.4,
    price: 300,
    originalPrice: 599,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "Tokyo Ghoul",
    img: "https://i.ibb.co/ZRjQJRN/Tokyo-Ghoul.jpg",
    author: "Sui Ishida",
    category: "Action",
    published: 2011,
    rating: 4.3,
    price: 500,
    originalPrice: 899,
    deliveryTime: "2-4 business days",
    ratings: 4.6
  }, {
    id: uuid(),
    title: "Black Clover",
    img: "https://i.ibb.co/QPVGSMB/black-clover.jpg",
    author: "Yūki Tabata",
    category: "Adventure",
    published: 2015,
    rating: 5,
    price: 280,
    originalPrice: 449,
    deliveryTime: "2-4 business days",
    ratings: 4.7
  },
  {
    id: uuid(),
    title: "Fairy Tail",
    img: "https://i.ibb.co/kcFGc6b/fairy-tail.jpg",
    author: "Hiro Mashima",
    category: "Adventure",
    published: 2006,
    rating: 4.3,
    price: 275,
    originalPrice: 399,
    deliveryTime: "2-4 business days",
    ratings: 4.7
  },
  {
    id: uuid(),
    title: "Hunter x Hunter",
    img: "https://i.ibb.co/drkBZ4S/hunter-x-hunter.jpg",
    author: "Yoshihiro Togashi",
    category: "Adventure",
    published: 1998,
    rating: 5,
    price: 300,
    originalPrice: 499,
    deliveryTime: "2-4 business days",
    ratings: 4.7
  },
  {
    id: uuid(),
    title: "Naruto Shippuden",
    img: "https://i.ibb.co/c8LwJw1/Naruto-Shippuden.png",
    author: "Masashi Kishimoto",
    category: "Adventure",
    published: 2007,
    rating: 5,
    price: 275,
    originalPrice: 399,
    deliveryTime: "2-4 business days",
    ratings: 4.7
  },
  {
    id: uuid(),
    title: "Tokyo Ghoul: re",
    img: "https://i.ibb.co/CPM1ZN0/Tokyo-Ghoul-re.jpg",
    author: "Sui Ishida",
    category: "Adventure",
    published: 2014,
    rating: 4.1,
    price: 320,
    originalPrice: 499,
    deliveryTime: "2-4 business days",
    ratings: 4.5
  },
  {
    id: uuid(),
    title: "Sword Art Online",
    img: "https://i.ibb.co/WHY0Kvs/Sword-Art-Online.png",
    author: "Reki Kawahara",
    category: "Action",
    published: 2012,
    rating: 4.5,
    price: 280,
    originalPrice: 449,
    deliveryTime: "2-4 business days",
    ratings: 4.7
  },
  {
    id: uuid(),
    title: "Demon Slayer",
    img: "https://i.ibb.co/3SNCDs8/Demon-Slayer-Kimetsu-no-Yaiba.jpg",
    author: "Koyoharu Gotouge",
    category: "Action",
    published: 2016,
    rating: 5,
    price: 300,
    originalPrice: 449,
    deliveryTime: "2-4 business days",
    ratings: 4.8
  },
  {
    id: uuid(),
    title: "Dragon Ball Super",
    img: "https://i.ibb.co/yPhftq9/Dragon-Ball-Super.jpg",
    author: "Akira Toriyama",
    category: "Action",
    published: 2015,
    rating: 5,
    price: 320,
    originalPrice: 499,
    deliveryTime: "2-4 business days",
    ratings: 4.5
  },
  {
    id: uuid(),
    title: "JoJo's Bizarre Adventure",
    img: "https://i.ibb.co/sWZZsCw/Jo-Jo-s-Bizarre-Adventure.jpg",
    author: "Hirohiko Araki",
    category: "Action",
    published: 1987,
    rating: 4.6,
    price: 300,
    originalPrice: 499,
    deliveryTime: "2-4 business days",
    ratings: 4.7
  },
  {
    id: uuid(),
    title: "Boruto",
    img: "https://i.ibb.co/0y08Qmx/Boruto-Naruto-Next-Generations.jpg",
    author: "Masashi Kishimoto",
    category: "Adventure",
    published: 2016,
    rating: 4.2,
    price: 320,
    originalPrice: 499,
    deliveryTime: "2-4 business days",
    ratings: 4.5
  },
  {
    id: uuid(),
    title: "The Promised Neverland",
    img: "https://i.ibb.co/TKsCbbw/The-Promised-Neverland.jpg",
    author: "Kaiu Shirai",
    category: "Drama",
    published: 2016,
    rating: 4.5,
    price: 280,
    originalPrice: 399,
    deliveryTime: "2-4 business days",
    ratings: 4.6
  },
  {
    id: uuid(),
    title: "Neon Genesis Evangelion",
    img: "https://i.ibb.co/THTKcvR/Neon-Genesis-Evangelion.jpg",
    author: "Hideaki Anno",
    category: "Action",
    published: 1995,
    rating: 4.4,
    price: 275,
    originalPrice: 399,
    deliveryTime: "2-4 business days",
    ratings: 4.7
  },
  {
    id: uuid(),
    title: "Cowboy Bebop",
    img: "https://i.ibb.co/sjxWRhD/Cowboy-Bebop.jpg",
    author: "Shinichirō Watanabe",
    category: "Action",
    published: 1998,
    rating: 4.7,
    price: 300,
    originalPrice: 499,
    deliveryTime: "2-4 business days",
    ratings: 4.8
  }


]
