import { v4 as uuid } from "uuid"

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    id: uuid(),
    title: "One Piece",
    img: "https://i.ibb.co/M6R0ym4/one-piece.webp",
    author: "Eiichiro Oda",
    category: "Adventure",
    published: 1997,
    rating: 4.1,
    price: 250,
    originalPrice: 399,
    discount: 23,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "Attack on Titan",
    img: "https://i.ibb.co/gwgsD62/Attack-of-titan.jpg",
    author: "Hajime Isayama",
    category: "Action",
    published: 2009,
    rating: 4.0,
    price: 275,
    originalPrice: 350,
    discount: 25,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "Naruto",
    img: "https://i.ibb.co/fDnMm5V/Naruto.jpg",
    author: "Masashi Kishimoto",
    category: "Adventure",
    published: 1999,
    rating: 3.3,
    price: 399,
    originalPrice: 200,
    discount: 30,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "Death Note",
    img: "https://i.ibb.co/H7zzSPK/Death-Note.jpg",
    author: "Tsugumi Ohba",
    category: "Drama",
    published: 2003,
    rating: 3.9,
    price: 650,
    originalPrice: 999,
    discount: 27,
    deliveryTime: "2-4 business days",
    ratings: 4.6
  },
  {
    id: uuid(),
    title: "Dragon Ball",
    img: "https://i.ibb.co/LvknnNs/ragon-Ball-Z.png",
    author: "Akira Toriyama",
    category: "Adventure",
    published: 1984,
    rating: 2.5,
    price: 599,
    originalPrice: 899,
    discount: 22,
    deliveryTime: "2-4 business days",
    ratings: 4.6
  },
  {
    id: uuid(),
    title: "Fullmetal Alchemist",
    img: "https://i.ibb.co/BC1kZDQ/Fullmetal-Alchemist.jpg",
    author: "Hiromu Arakawa",
    category: "Action",
    published: 2001,
    rating: 4.1,
    price: 425,
    originalPrice: 799,
    discount: 22,
    deliveryTime: "2-4 business days",
    ratings: 4.6
  },
  {
    id: uuid(),
    title: "Bleach",
    img: "https://i.ibb.co/ct0NYbF/Bleach.jpg",
    author: "Tite Kubo",
    category: "Action",
    published: 2001,
    rating: 3.2,
    price: 200,
    originalPrice: 499,
    discount: 26,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "One Punch Man",
    img: "https://i.ibb.co/7XSgkcK/One-Punch-Man.jpg",
    author: "ONE",
    category: "Drama",
    published: 2009,
    rating: 3.7,
    price: 250,
    originalPrice: 399,
    discount: 32,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "My Hero Academia",
    img: "https://i.ibb.co/xs6J8QN/My-Hero-Academia.jpg",
    author: "Kohei Horikoshi",
    category: "Drama",
    published: 2014,
    rating: 3.4,
    price: 300,
    originalPrice: 599,
    discount: 19,
    deliveryTime: "2-4 business days",
    ratings: 4.6,
  },
  {
    id: uuid(),
    title: "Tokyo Ghoul",
    img: "https://i.ibb.co/ZRjQJRN/Tokyo-Ghoul.jpg",
    author: "Sui Ishida",
    category: "Action",
    published: 2011,
    rating: 4.3,
    price: 500,
    originalPrice: 899,
    discount: 33,
    deliveryTime: "2-4 business days",
    ratings: 4.6
  }
]
